os:
  - linux
language:
  - c
  - go
compiler:
  - gcc
install:
  - wget https://github.com/mcellteam/nutmeg/archive/master.zip
  - unzip master.zip
  - cd nutmeg
  - go build
script: cd ./src && ./bootstrap && ./configure && make
