os:
  - linux
language:
  - c
  - go
compiler:
  - gcc
install:
  - mkdir go
  - export GOPATH=${TRAVIS_BUILD_DIR}/go
  - echo $GOPATH
  - wget https://github.com/mcellteam/nutmeg/archive/master.zip
  - unzip master.zip
  - cd nutmeg-master
  - go get
  - go build
script: cd ./src && ./bootstrap && ./configure && make
