os:
  - linux
language:
  - c
  - go
compiler:
  - gcc
install:
  - mkdir go
  - export GOPATH=$HOME
  - echo $GOPATH
  - wget https://github.com/mcellteam/nutmeg/archive/master.zip
  - unzip master.zip
  - mv nutmeg-master nutmeg
  - cd nutmeg
  - go get github.com/mcellteam/nutmeg/src/engine
  - go get github.com/mcellteam/nutmeg/src/misc
  - go get github.com/mcellteam/nutmeg/src/tomlParser
  - go build
  - echo "testDir = \"${TRAVIS_BUILD_DIR}/nutmeg/tests\"" > nutmeg.conf
  - echo "includeDir = \"${TRAVIS_BUILD_DIR}/nutmeg/toml_includes\"" >> nutmeg.conf
  - echo "mcellPath = \"${TRAVIS_BUILD_DIR}/src/mcell\"" >> nutmeg.conf
  - cat nutmeg.conf
  - ls
  - cd ${TRAVIS_BUILD_DIR}
  - ls
script: cd ./src && ./bootstrap && ./configure && make
after_success:
  - cd ${TRAVIS_BUILD_DIR}/nutmeg
  - travis_wait ./nutmeg -r=1:10
  - travis_wait ./nutmeg -r=10:20
  - travis_wait ./nutmeg -r=20:30
  - travis_wait ./nutmeg -r=40:50
  - travis_wait ./nutmeg -r=50:60
  - travis_wait ./nutmeg -r=60:70
  - travis_wait ./nutmeg -r=70:80
  - travis_wait ./nutmeg -r=80:90
  - travis_wait ./nutmeg -r=90:100
  - travis_wait ./nutmeg -r=100:110
  - travis_wait ./nutmeg -r=110:120
  - travis_wait ./nutmeg -r=120:130
  - travis_wait ./nutmeg -r=130:140
  - travis_wait ./nutmeg -r=140:150
  - travis_wait ./nutmeg -r=150:160
  - travis_wait ./nutmeg -r=160:170
  - travis_wait ./nutmeg -r=170:179
