os:
  - linux
language:
  - c
  - go
compiler:
  - gcc
install:
  - mkdir go
  - export GOPATH=$HOME
  - echo $GOPATH
  - wget https://github.com/mcellteam/nutmeg/archive/master.zip
  - unzip master.zip
  - mv nutmeg-master nutmeg
  - cd nutmeg
  - go get github.com/mcellteam/nutmeg/src/engine
  - go get github.com/mcellteam/nutmeg/src/misc
  - go get github.com/mcellteam/nutmeg/src/tomlParser
  - go build
  - echo 'testDir = "/home/travis/build/jczech/mcell/nutmeg/tests"\nincludeDir = "/home/travis/build/jczech/mcell/nutmeg/toml_includes"\nmcellPath = "/home/travis/build/jczech/mcell/src/mcell"\n' > nutmeg.conf
  - cat nutmeg.conf
  - ls
  - cd ${TRAVIS_BUILD_DIR}
  - ls
script: cd ./src && ./bootstrap && ./configure && make
after_success:
  - cd ${TRAVIS_BUILD_DIR}/nutmeg
  - ./nutmeg -r=all
