os:
  - linux
  - osx
language:
  - c
  - go
compiler:
  - gcc
  - clang
install:
  # This is just for building and setting up nutmeg
  - mkdir go
  - export GOPATH=$HOME
  - echo $GOPATH
  - wget https://github.com/mcellteam/nutmeg/archive/master.zip
  - unzip master.zip
  - mv nutmeg-master nutmeg
  - cd nutmeg
  - go get github.com/mcellteam/nutmeg/src/engine
  - go get github.com/mcellteam/nutmeg/src/misc
  - go get github.com/mcellteam/nutmeg/src/tomlParser
  - go build
  - echo "testDir = \"${TRAVIS_BUILD_DIR}/nutmeg/tests\"" > nutmeg.conf
  - echo "includeDir = \"${TRAVIS_BUILD_DIR}/nutmeg/toml_includes\"" >> nutmeg.conf
  - echo "mcellPath = \"${TRAVIS_BUILD_DIR}/src/mcell\"" >> nutmeg.conf
  - cd ${TRAVIS_BUILD_DIR}
script: 
  # This first line is what builds MCell. The rest is for nutmeg
  - cd ./src && ./bootstrap && ./configure && make
  - cd ${TRAVIS_BUILD_DIR}/nutmeg
  # Grab the number of tests in nutmeg testsuite
  - end=$(./nutmeg -l | tail -n 1 | grep --color=never -o "[1-9]*")
  # We need to use travis_wait since some of these tests take a long time
  - for i in $(seq 1 $end); do travis_wait ./nutmeg -r=$i; done
